//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::app_setting::Entity as AppSetting;
pub use super::project::Entity as Project;
pub use super::project_detail::Entity as ProjectDetail;
